//! Generates the PipeWire filter-chain config: 20 fixed biquad slots (slot 0 = lowshelf,
//! 1..18 = peaking, 19 = highshelf) plus a preamp gain stage, so switching presets never
//! needs a different graph shape.
//!
//! NOTE (see NOTES.md): runtime `Props` writes to a live filter-chain node don't reach the
//! graph on this PipeWire build (verified exhaustively in Fase 0). So unlike the original
//! design, control values are baked in here as the *initial* config values, and applying a
//! preset means regenerating this file and restarting PipeWire — not a live Props write.

use crate::dsp::BandType;
use crate::preset::{Band, Preset};
use anyhow::{Context, Result};
use std::path::PathBuf;

pub const N_PEAKING_SLOTS: usize = 18;
pub const N_SLOTS: usize = N_PEAKING_SLOTS + 2;

pub const SINK_NODE_NAME: &str = "peq";
const PLAYBACK_NODE_NAME: &str = "peq_out";
const PREAMP_NODE: &str = "peq_preamp";

fn band_node_name(slot: usize) -> String {
    format!("peq_band_{slot:02}")
}

pub struct Slot {
    pub node: String,
    pub label: &'static str,
    pub freq: f64,
    pub q: f64,
    pub gain: f64,
}

/// Map a preset's bands onto the 20 fixed slots. Extra peaking bands beyond
/// [`N_PEAKING_SLOTS`] are dropped defensively (the AutoEQ importer already truncates,
/// but a hand-edited preset TOML could still have too many).
pub fn slots_for(preset: &Preset) -> Vec<Slot> {
    let mut lowshelf: Option<&Band> = None;
    let mut highshelf: Option<&Band> = None;
    let mut peakings: Vec<&Band> = Vec::new();
    for b in &preset.bands {
        if !b.enabled {
            continue;
        }
        match b.kind {
            BandType::Lowshelf => lowshelf.get_or_insert(b),
            BandType::Highshelf => highshelf.get_or_insert(b),
            BandType::Peaking => {
                if peakings.len() < N_PEAKING_SLOTS {
                    peakings.push(b);
                }
                continue;
            }
        };
    }

    let mut slots = Vec::with_capacity(N_SLOTS);
    slots.push(Slot {
        node: band_node_name(0),
        label: "bq_lowshelf",
        freq: lowshelf.map_or(100.0, |b| b.freq),
        q: lowshelf.map_or(0.7, |b| b.q),
        gain: lowshelf.map_or(0.0, |b| b.gain),
    });
    for i in 0..N_PEAKING_SLOTS {
        let b = peakings.get(i).copied();
        slots.push(Slot {
            node: band_node_name(i + 1),
            label: "bq_peaking",
            freq: b.map_or(1000.0, |b| b.freq),
            q: b.map_or(0.7, |b| b.q),
            gain: b.map_or(0.0, |b| b.gain),
        });
    }
    slots.push(Slot {
        node: band_node_name(N_SLOTS - 1),
        label: "bq_highshelf",
        freq: highshelf.map_or(10_000.0, |b| b.freq),
        q: highshelf.map_or(0.7, |b| b.q),
        gain: highshelf.map_or(0.0, |b| b.gain),
    });
    slots
}

/// Render the full `context.modules` filter-chain config text for `preset`.
pub fn render(preset: &Preset) -> String {
    let slots = slots_for(preset);
    let mult = 10f64.powf(preset.preamp_db / 20.0);

    let mut nodes = String::new();
    nodes.push_str(&format!(
        "                    {{ type = builtin name = {PREAMP_NODE} label = linear\n\
         \x20                     control = {{ \"Mult\" = {mult:.6} \"Add\" = 0.0 }} }}\n"
    ));
    for s in &slots {
        nodes.push_str(&format!(
            "                    {{ type = builtin name = {node} label = {label}\n\
             \x20                     control = {{ \"Freq\" = {freq:.3} \"Q\" = {q:.3} \"Gain\" = {gain:.3} }} }}\n",
            node = s.node,
            label = s.label,
            freq = s.freq,
            q = s.q,
            gain = s.gain,
        ));
    }

    let mut links = String::new();
    links.push_str(&format!(
        "                    {{ output = \"{PREAMP_NODE}:Out\" input = \"{}:In\" }}\n",
        slots[0].node
    ));
    for pair in slots.windows(2) {
        links.push_str(&format!(
            "                    {{ output = \"{}:Out\" input = \"{}:In\" }}\n",
            pair[0].node, pair[1].node
        ));
    }

    format!(
        "# generated by `peq` - do not edit by hand, use `peq <preset>` / `peq edit <preset>`\n\
         # active preset: {name}\n\
         context.modules = [\n\
         \x20   {{ name = libpipewire-module-filter-chain\n\
         \x20       args = {{\n\
         \x20           node.description = \"peq\"\n\
         \x20           media.name        = \"peq\"\n\
         \x20           filter.graph = {{\n\
         \x20               nodes = [\n\
         {nodes}\
         \x20               ]\n\
         \x20               links = [\n\
         {links}\
         \x20               ]\n\
         \x20           }}\n\
         \x20           audio.channels = 2\n\
         \x20           audio.position = [ FL FR ]\n\
         \x20           capture.props = {{\n\
         \x20               node.name   = \"{SINK_NODE_NAME}\"\n\
         \x20               media.class = Audio/Sink\n\
         \x20           }}\n\
         \x20           playback.props = {{\n\
         \x20               node.name    = \"{PLAYBACK_NODE_NAME}\"\n\
         \x20               node.passive = true\n\
         \x20           }}\n\
         \x20       }}\n\
         \x20   }}\n\
         ]\n",
        name = preset.name,
    )
}

pub fn config_file_path() -> PathBuf {
    PathBuf::from(std::env::var("HOME").unwrap_or_else(|_| "/".to_string()))
        .join(".config/pipewire/pipewire.conf.d/99-peq.conf")
}

/// Write the config for `preset`, creating the conf.d directory if needed.
pub fn write_config(preset: &Preset) -> Result<PathBuf> {
    let path = config_file_path();
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    }
    std::fs::write(&path, render(preset)).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

/// A silent preset (all gains 0, 0dB preamp) - used by `peq init` and `peq off`.
pub fn silent_preset(name: &str) -> Preset {
    Preset::new(name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::preset::Band;

    fn sample_preset() -> Preset {
        Preset {
            name: "test".into(),
            preamp_db: -6.0,
            match_patterns: vec![],
            bands: vec![
                Band {
                    kind: BandType::Lowshelf,
                    freq: 105.0,
                    gain: -3.5,
                    q: 0.7,
                    enabled: true,
                },
                Band {
                    kind: BandType::Peaking,
                    freq: 1000.0,
                    gain: 2.0,
                    q: 1.0,
                    enabled: true,
                },
                Band {
                    kind: BandType::Highshelf,
                    freq: 8000.0,
                    gain: 1.0,
                    q: 0.7,
                    enabled: true,
                },
            ],
            ..Preset::new("test")
        }
    }

    #[test]
    fn has_21_nodes_and_20_links() {
        let text = render(&sample_preset());
        assert_eq!(text.matches("type = builtin").count(), 21);
        assert_eq!(text.matches("{ output =").count(), 20);
    }

    #[test]
    fn slot_types_match_layout() {
        let slots = slots_for(&sample_preset());
        assert_eq!(slots.len(), N_SLOTS);
        assert_eq!(slots[0].label, "bq_lowshelf");
        assert_eq!(slots[N_SLOTS - 1].label, "bq_highshelf");
        assert!(slots[1..N_SLOTS - 1]
            .iter()
            .all(|s| s.label == "bq_peaking"));
        // the one peaking band from the preset landed in the first peaking slot
        assert_eq!(slots[1].gain, 2.0);
    }

    #[test]
    fn unused_slots_are_passthrough() {
        let slots = slots_for(&sample_preset());
        assert_eq!(slots[2].gain, 0.0); // second peaking slot unused
    }

    #[test]
    fn disabled_bands_are_omitted_from_slots() {
        let mut preset = Preset::new("disabled");
        preset.bands = vec![
            Band {
                kind: BandType::Lowshelf,
                freq: 120.0,
                gain: 6.0,
                q: 0.7,
                enabled: false,
            },
            Band {
                kind: BandType::Peaking,
                freq: 1000.0,
                gain: 2.0,
                q: 1.0,
                enabled: true,
            },
        ];

        let slots = slots_for(&preset);
        assert_eq!(slots[0].label, "bq_lowshelf");
        assert_eq!(slots[0].gain, 0.0);
        assert_eq!(slots[1].gain, 2.0);
    }
}
